[package]
name = "blinky-nrf52840-mdk"
version = "0.1.0"
edition = "2021"

[dependencies]
blinky = { path = "../blinky" }
cortex-m-rt = "0.6"
panic-halt = "0.2"
nrf52840-hal = { version = "0.15.0", features = ["rt"] }
nrf52840-pac = "0.11.0"
void = { version = "1.0.2", default-features = false }