[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "xtensa-esp32-elf-gdb -q -x openocd.gdb"

[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }